---
name: CI
on: [push]
jobs:
  test-tgz:
    name: Test .tar.gz
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: Add $GOPATH/bin to $PATH
        run: |
          mkdir -p $(go env GOPATH)/bin/
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Get bin file
        uses: supercaracal/go-mod-dl-action@master
        with:
          url: "https://github.com/Songmu/goxz/releases/download/v0.6.0/goxz_v0.6.0_linux_amd64.tar.gz"
        id: get-bin

      - name: Move bin file
        run: mv ${{ steps.get-bin.outputs.file }} $(go env GOPATH)/bin/

      - name: Check bin file
        run: type goxz

  test-zip:
    name: Test .zip
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: Add $GOPATH/bin to $PATH
        run: |
          mkdir -p $(go env GOPATH)/bin/
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Get bin file
        uses: supercaracal/go-mod-dl-action@master
        with:
          url: "https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_darwin_amd64.zip"
        id: get-bin

      - name: Move bin file
        run: mv ${{ steps.get-bin.outputs.file }} $(go env GOPATH)/bin/

      - name: Check bin file
        run: type ghr
